blog/urls.py
from django.urls import path;
from . import views;

urlpatterns = [
    path('', views.BlogView.as_view(), name="blog"),
    path('category/<str:tag_filter>/<slug:description_slug>', views.blog_category_view, name="blog-category"),
    path('<int:pk>/<title>', views.PostView.as_view(), name="post"),
]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
]

portfolio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('projects/', include('projects.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projects/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ProjectView.as_view(), name="projects")
]

blog/models.py
from django.db import models
from ckeditor.fields import RichTextField

languages = [
    ("ES", "Español"),
    ("EN", "English"),
]

# Create your models here.
class Author(models.Model):
    first_name = models.CharField(max_length=36)
    last_name = models.CharField(max_length=36)
    email = models.CharField(max_length=150)

    def __str__(self):
        return self.first_name + " " + self.last_name

class Tag(models.Model):
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.description

class Post(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    body = RichTextField(blank=True)
    date_published = models.DateField()
    repo_link = models.CharField(max_length=255, blank=True, null=True)
    banner_img = models.ImageField(upload_to="blog/banner_img", blank=True, null=True)
    card_img = models.ImageField(upload_to="blog/card_img", blank=True, null=True)
    lang = models.CharField(max_length=2, choices=languages, default="EN")
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    tag = models.ManyToManyField(Tag)

    class Meta:
        ordering = ['-date_published']

    def __str__(self):
        return self.title

    def get_tags(self):
        tags = [tag.description for tag in self.tag.all()]
        return tags

home/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models
from blog.models import Post

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=255)
    showcase = models.BooleanField(default=False)
    live_demo = models.CharField(max_length=255, null=True, blank=True)
    post = models.OneToOneField(
        Post,
        on_delete=models.CASCADE,
        primary_key=True,
    )

    def __str__(self):
        return self.title

home/forms.py
from django import forms

TOPICS = [
    ("DATA", "Data Science/Data Analysis"),
    ("WEBFRONT", "Front-end Work"),
    ("WEBBACK", "Back-end Work"),
]

class ContactForm(forms.Form):
    topic = forms.ChoiceField(widget=forms.Select(attrs={'class': 'form-select'}), choices=TOPICS)
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), max_length=200)
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}), max_length=200)
    message = forms.CharField(widget = forms.Textarea(attrs={'class': 'form-control'}), max_length=2000)

blog/views.py
from django.shortcuts import render
from .models import Author, Tag, Post
from django.views.generic import ListView, DetailView

# Create your views here.
class BlogView(ListView):
    paginate_by = 4
    model = Post
    fields = "__all__"
    template_name = "blog/blog.html"

    def get_context_data(self):
        context = super().get_context_data()
        context["posts"] = Post.objects.all()
        return context

class PostView(DetailView):
    model = Post
    template_name = "blog/post.html"

def blog_category_view(request, tag_filter, description_slug):
    filtered_posts = Post.objects.all().filter(tag__id=tag_filter)
    context = { 'page_obj' : filtered_posts }
    return render(request, 'blog/blog.html', context)

home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from blog.models import Post
from projects.models import Project
from django.core.mail import send_mail, BadHeaderError
from .forms import ContactForm

# Create your views here.
def home(request):
    context = {}
    context["projects"] = Project.objects.all()
    context["posts"] = Post.objects.all()
    return render(request, 'home/home.html', context)

def about(request):
    return render(request, 'home/about.html')

def contact(request):
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = "Inquiry From malcomcal.com"
            body = {
                'topic' : form.cleaned_data['topic'],
                'name' : form.cleaned_data['name'],
                'email' : form.cleaned_data['email'],
                'message' : form.cleaned_data['message'],
            }
            message = "\n".join(body.values())

            try:
                send_mail(subject, message, 'arkmalcom@gmail.com', ['arkmalcom@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header.')
            return redirect ("home")
    form = ContactForm()
    return render(request, 'home/contact.html', {'form':form})

projects/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.
class ProjectView(TemplateView):
    template_name = "projects/projects.html"

blog/templates/blog/blog.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}
<div class="bg-image bg-image-top" style="background-image: url('/static/home/img/blog-banner.jpg'); background-size: cover;">
<div class="container-fluid background-container-bottom background-container">
<div class="container d-flex align-items-center" style="height: 40vh;">
    <div class="row">
        <div class="col">
            <h1 class="fade-in-text">Blog<span style="color: var(--color-accent); font-family: 'Style Script', cursive;">.</span></h1>
            <p>My blog contains a post for every project I've worked on. 
                In each article, I talk about the things I learned while working on those projects.
                I also blog about some of my favorite hobbies, including books and cooking.
            </p>         
        </div>
    </div>
</div>
</div>
</div>
<div class="container-fluid">
    <div class="row pt-3 pt-lg-1">
        <div class="col-lg-3 col-sm-6 pb-2 pb-lg-0">
        <div class="category-img">
            <a href="{% url 'blog-category' tag_filter=1 description_slug='Data Science'|slugify %}">
            <img class="img-responsive custom-img rounded" src="{% static 'home/img/data-science.jpg'%}">
            <h2>Data Science</h2></a>
        </div>
        </div>
        <div class="col-lg-3 col-sm-6 pb-2 pb-lg-0">
            <div class="category-img">
                <a href="{% url 'blog-category' tag_filter=14 description_slug='Web Development'|slugify %}">
                <img class="img-responsive custom-img rounded" src="{% static 'home/img/web-development.jpg'%}">
                <h2>Web Development</h2></a>
            </div>
            </div>
        <div class="col-lg-3 col-sm-6 pb-2 pb-lg-0">
                <div class="category-img">
                <a href="{% url 'blog-category' tag_filter=15 description_slug='Books'|slugify %}">
                <img class="img-responsive custom-img rounded" src="{% static 'home/img/books.jpg'%}">
                <h2>Books</h2></a>
                </div>
        </div>
        <div class="col-lg-3 col-sm-6 pb-2 pb-lg-0">
             <div class="category-img">
                <a href="{% url 'blog-category' tag_filter=16 description_slug='Cooking'|slugify %}">
                <img class="img-responsive custom-img rounded" src="{% static 'home/img/cooking.jpg'%}">
                <h2>Cooking</h2></a>
            </div>
        </div>
    </div>
</div>
<div class="container content-container">
    {% for post in page_obj %}
<a href="{% url 'post' pk=post.pk title=post.title|slugify %}">
<div class="container mb-4 mt-2 blog-grow">
    <div class="row pt-5">
        <div class="col text-center pt-3">
            <img class="img-responsive blog-img" src="{{post.card_img.url}}">
        </div>
    </div>
    <div class="row">
            <div class="col text-center pt-5">
                {% for tag in post.tag.all %}
                <a href="{% url 'blog-category' tag_filter=tag.id description_slug=tag.description|slugify %}"><button class="btn btn-secondary mx-1 mt-2">{{tag.description}}</button></a>
                {% endfor %}
                <a href="{% url 'post' pk=post.pk title=post.title|slugify %}"><h2 class="pt-3">{{post.title}}</h2></a>
                <div class="row">
                    <div class="col-lg-3 offset-lg-3">
                        <h3 class="pt-2">By: {{post.author}}</h3>
                    </div>
                    <div class="col-lg-3">
                        <h3 class="pt-2">Published: {{post.date_published}}</h3>
                    </div>
                </div>
                <p>{{post.description}}</p>
            </div>
    </div>

</div>
</a>
    {% endfor %}
{% if is_paginated %}
<div class="pagination d-flex justify-content-center">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
</div>
{% endif %}
</div>
{% endblock %}

blog/templates/blog/index.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <h1>Blog</h1>
        </div>
    </div>
    <div class="row">
        {% for post in posts %}
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">
                            <a href="{% url 'post' pk=post.pk title=post.title|slugify %}">{{post.title}}</a>
                        </h5>
                        <p class="card-text">
                            By: {{post.author}}
                        </p>
                        <p class="card-text">
                            Published: {{post.date_published}}
                        </p>
                        <p class="card-text">
                            Tags: 
                             {% for tag in post.tag.all %}
                             {% if forloop.last %}
                             {{tag}}.
                             {% else %}
                             {{tag}},
                             {% endif %} 
                             {% endfor %}
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

blog/templates/blog/post.html
{% extends "home/base.html" %}

{% load static %}

{% block content %}

<div class="container section">
    {% if post.banner_img != null %}
    <div class="row">
        <div class="banner-img-container" style="background-image: url({{post.banner_img.url}});">
        </div>
    </div>
    {% endif %}
    <div clas="row">
        <div class="col text-center">
            <h1>{{post.title}}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col text-center">
            <h3>By: {{post.author}}</h3>
        </div>
        <div class="col text-center">
            <h3>Published: {{post.date_published}}</h3>
        </div>
    </div>
    {% if post.repo_link != null %}
    <div class="row">
        <div class="col text-center">
            <a href={{post.repo_link}} target="_blank"><button class="btn btn-primary">Source Code <i class="fas fa-arrow-right"></i></button></a>
        </div>
    </div>
    {% endif %}
    <div class="row">
        <div class="col">
            {{post.body|safe}}
        </div>
    </div>
</div>

{% endblock %}

home/templates/home/about.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}
<div class="bg-image bg-image-top" style="background-image: url('/static/home/img/about-banner.jpg'); background-size: cover; background-position: 15% 0%;">
    <div class="container-fluid background-container-bottom background-container">
    <div class="container d-flex align-items-center" style="height: 40vh;">
        <div class="row w-100 text-lg-end">
            <div class="col">
                <h1 class="fade-in-text">About Me<span style="color: var(--color-accent); font-family: 'Style Script', cursive;">.</span></h1>
            </div>
        </div>
    </div>
</div>
</div>
<div class="container content-container pt-5">
    <div class="row">
        <div class="col">
            <h2>
                How it all began<span style="color: var(--color-accent); font-family: 'Style Script', cursive;">.</span>
            </h2>
            <p>Hi! My name is Malcom. I was born in Argentina and grew up in New York.
                Now, I live and work in the Dominican Republic. Ever since I was a child, I've loved technology and science.
                From the time I got my first computer, I've loved tinkering with electronics. Even something as simple as editing batch files
                felt magical to a young me.
            </p>
            <p>
                I remember how excited I was when I figured out I could edit Windows' autoexec.bat to echo a custom
                greeting for me that would show up every time I booted my machine. I also remember the feeling of utter dread
                after irreversibly altering or deleting an important system file,
                back during a time when file recovery and system restore points were not very user-friendly.
            </p>
        </div>
    </div>
    <div class="row pt-2">
        <div class="col">
            <h2 class="text-lg-end">
                What I love<span style="color: var(--color-accent); font-family: 'Style Script', cursive;">.</span>
            </h2>
            <p>
                Technology and science were never my only passions. From a young age I've had a great love of music.
                Like many, I got my start in music with childhood piano lessons. During my teenage years I learned to play
                the guitar. These days, I like to transition between several different instruments, though my favorite
                at the moment is the bass.
            </p>
            <p>
                Aside from music, I consider myself an avid reader. Whether it's books on mythology, self-improvement, or
                the occasional sci-fi or fantasy novel, I spend a large chunk of my free time exploring the world through reading.
                Lastly, I enjoy learning to cook new dishes. Every week I try to learn to either bake or cook something completely new.
            </p>
        </div>
        <div class="col-5 d-none d-lg-block">
            <div class="img-responsive img-blur background-container" style="background-image: url('/static/home/img/about-music.png');">
            </div>
        </div>
    </div>
    <div class="row pt-2">
        <div class="col">
            <h2 class="text">
                My abilities<span style="color: var(--color-accent); font-family: 'Style Script', cursive;">.</span>
            </h2>
            <p>
                Developers often boast about the many languages they can code in or the many techs they're proficient in --
                and don't worry, I will do that, as well.
                However, I think it's important to highlight the skill that has made me not only want to pursue a career in technology,
                but also what I think makes great programmers: adaptability. I'm an incredibly quick learner. With a look through some
                documentation and just a bit of hands-on practice, I can learn a new technology very rapidly. Adapting to mistakes
                and learning from them quickly isn't just a characteristic I brag about to entice potential employers: it's the very
                element that drives my passion for technology and science.
            </p>
            <p>
                This is a field that changes and advances at breakneck speed, and I love it. I might be tidying data with R one day,
                and tweaking a machine learning model in Python to achieve a 0.1% increase in accuracy the next. I may have worked with
                a front-end framework a year ago that is completely different today. It's a discipline that punishes stagnation and
                conformity. You must be willing to learn in order to grow.
            </p>
            <p>
                I have a love for all things Python. This website was made using the Django framework. It's hosted on <a href="http://pythonanywhere.com">
                pythonanywhere.com</a>. Though it is far and away my favorite language, many of the projects hosted on this site were created using different
                frameworks. My preferred field of work is in data analysis and data science. As such, most of the tools I've chosen to specialize in
                are analytical in nature. Python, R, SQL, PowerBI, and Tableau are some of the tools I've used to carry out data analysis. As far as
                web development: ReactJS is my favored tool for front-end work, whereas languages such as C# and
                Python are my preferred options for back-end work.
            </p>
        </div>
    </div>
    <div class="row pt-2">
        <div class="col-5 d-none d-lg-block">
            <div class="img-responsive img-blur background-container" style="background-image: url('/static/home/img/portrait.png');">
            </div>
        </div>
        <div class="col">
            <h2 class="text-lg-end">
                My mission<span style="color: var(--color-accent); font-family: 'Style Script', cursive;">.</span>
            </h2>
            <p>
                I strongly believe that feeding our passions fuels our self-growth. As such, my mission as a professional is
                to always find room for improvement. A one percent improvement may not seem like a lot as an isolated number,
                but accumulated additively over a month means you are now 30% better. Imagine the effect of such small daily
                increments on an entire team.
            </p>
            <p>
                Due to my personal philosophy of continuous improvement, I can assure you that I will bring my best to any
                project that I work on. More than that, the bar for what I consider "best" will constantly shift upwards, as I seek
                ways to consistently grow and improve not just myself, but any team I'm a part of.
            </p>
        </div>
    </div>
</div>
<div class="container text-center pb-3 pt-3">
    <div class="row">
        <div class="col">
            <h1>Want to discuss your next project<span style="color: var(--color-accent); font-family: 'Bebas Neue', cursive;">?</span></h1>
            <a href="{% url 'contact' %}" class="disabled"><button class="btn btn-primary">Contact Me <i class="fas fa-arrow-right"></i></button></a>
        </div>
    </div>
</div>
{% endblock %}

home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="dark-theme">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/css/fa-icons.css' %}" />
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}" />
    {% block head %}
    <title>Home</title>
    {% endblock %}
</head>
<body>
  <nav class="navbar navbar-expand-lg pb-0 pt-0">
    <div class="container-fluid">
      <a class="navbar-brand px-3" href="{% url 'home' %}">Malcom Calivar<span style="color: var(--color-accent)">.</span></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"><i class="fas fa-bars"></i></span>
      </button>
      <button class="theme-switch" aria-label="toggle theme" onclick="switchTheme()">
        <i class="fas fa-adjust"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'home' %}active{% endif %}" href="{% url 'home' %}">Home</a>
          </li>
          <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle {% if request.resolver_match.url_name == 'projects' %}active{% endif %}" href="{% url 'projects' %}" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Projects
            </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Data Science</a></li>
            <li><a class="dropdown-item" href="#">Web Development</a></li>
            <li><a class="dropdown-item" href="#">Others</a></li>
          </ul> -->
        </li>
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'blog' or request.resolver_match.url_name == 'post' or request.resolver_match.url_name == 'blog-category' %}active{% endif %}" href="{% url 'blog' %}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'about' %}active{% endif %}" href="{% url 'about' %}">About</a>
          </li>
        <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'contact' %}active{% endif %}" href="{% url 'contact' %}">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
    {% block content %}

    {% endblock %}
    <footer class="footer mt-auto">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <h3>Quick links:</h3>
                    <ul class="list-group">
                        <li class="list-group-item"><a href="{% url 'blog' %}">Blog</a></li>
                        <li class="list-group-item"><a href="{% url 'about' %}">About</a></li>
                        <li class="list-group-item"><a href="{% url 'contact' %}">Contact</a></li>
                    </ul>
                </div>
                <div class="col-md-3 offset-md-6 mt-5">
                    <h3 class="signature text-center">Malcom Calivar<span style="color: var(--color-accent)">.</span></h3>
                    <div class="row">
                        <div class="col text-center">
                            <a href="https://www.linkedin.com/in/malcom-calivar/"><i class="fab fa-linkedin"></i></a>
                        </div>
                        <div class="col text-center">
                            <a href="https://github.com/arkmalcom"><i class="fab fa-github"></i></a>
                        </div>
                        <div class="col text-center">
                            <a href="mailto:arkmalcom@gmail.com"><i class="far fa-envelope"></i></a>
                        </div>
                    </div>
                </div>
                <div class="row w-100 text-center" style="border-top: 1px solid var(--color-secondary)">
                  <div class="col">
                    <small class="text-muted">Copyright © 2021 Malcom Calivar.</small>
                    <p><small class="text-muted">Stock images courtesy of <a class="text-muted" style="font-size: 14px;" href="http://pexels.com">
                      pexels.com
                    </a></small></p>
                  </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    <script src="{% static 'home/main.js' %}"></script>
</body>
</html>

home/templates/home/blog.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <h1>Blog</h1>
        </div>
    </div>
</div>
{% endblock %}

home/templates/home/contact.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}
<div class="bg-image bg-image-top" style="background-image: url('/static/home/img/contact-banner.jpg'); background-size: cover;">
    <div class="container-fluid background-container-bottom background-container">
    <div class="container d-flex align-items-center" style="height: 40vh;">
        <div class="row">
            <div class="col">
                <h1 class="fade-in-text">Contact Me<span style="color: var(--color-accent); font-family: 'Style Script', cursive;">.</span></h1>
                <p>If you're interested in hiring me, you may contact me via my <a href="https://linkedin.com/malcom-calivar">LinkedIn</a> page, 
                    or by filling out the form below:
                </p>         
            </div>
        </div>
    </div>
    </div>
</div>

<div class="container content-container w-75">
    <form method="POST">
        <div class="form-group">
            {% csrf_token %}
            <label class="form-label pt-4 pb-1" for="id_topic">How can I help you?</label>
            {{form.topic}}
            <label class="form-label pt-4 pb-1" for="id_message">Describe your project</label>
            {{form.message}}
            <label class="form-label pt-4 pb-1" for="id_name">Your name</label>
            {{form.name}}
            <label class="form-label pt-4 pb-1" for="id_email">Your E-mail</label>
            {{form.email}}
            <button class="btn btn-primary w-100 mt-4" type="submit">Contact Me <i class="fas fa-arrow-right"></i></button>
        </div>
    </form>
</div>
{% endblock %}

home/templates/home/projects.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <h1>Projects</h1>
        </div>
    </div>
</div>
{% endblock %}

projects/templates/projects/projects.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
            <h1>Projects</h1>
        </div>
    </div>
</div>

{% endblock %}